name = "OneTwoTree"
uuid = "ba1e7b89-03b6-4273-a638-c99556bacf5e"
authors = ["Jakob Balasus <balasus@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
julia = "1.10"
