name = "OneTwoTree"
uuid = "ba1e7b89-03b6-4273-a638-c99556bacf5e"
authors = ["Jakob Balasus <balasus@campus.tu-berlin.de>, Eloi Sandt <eloi.sandt@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.10"
