name = "OneTwoTree"
uuid = "ba1e7b89-03b6-4273-a638-c99556bacf5e"
authors = ["Jakob Balasus <balasus@campus.tu-berlin.de>, Eloi Sandt <eloi.sandt@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"

[compat]
julia = "1.10"
